name: Foresight Integration

on: [push, workflow_dispatch]

env: 
  BRANCH_NAME: auto-upstream-merge
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH_NAME }}
          lfs: true
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
        
      - name: Add Jacoco Configuration to Gradle
        run: |
          echo "
          test {
            finalizedBy jacocoTestReport
          }
          jacocoTestReport {
            reports {
              xml.enabled true
              xml.destination = file(\"\${buildDir}/reports/jacoco/result.xml\")
              html.enabled false
              csv.enabled false
            }
          }
          " >> build.gradle
      
      - name: Run Gradle Build
        run: ./gradlew clean build --warning-mode all --stacktrace
      
      - name: Foresight Test Report Uploader
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-result-junit
          path: build/test-results/test/*.xml

      - name: Foresight Coverage Report Uploader
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: coverage-artifact
          path: build/reports/jacoco/*.xml