name: build-foresight-maven-jacoco-sample

on: [push, workflow_dispatch]

env:
  BRANCH_NAME: auto-upstream-merge
  FORESIGHT_UPLOADER_SIGNER_URL: https://upload.service.runforesight.us
  WORKFLOW_TELEMETRY_BASE_URL: https://api.service.runforesight.us

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        with:
          api_key: ${{ secrets.FORESIGHT_API_KEY }}
      
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH_NAME }}
          lfs: true
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
        
      - name: Add Jacoco Configuration to Gradle
        run: |
          echo "
          test {
            finalizedBy jacocoTestReport
          }
          jacocoTestReport {
            reports {
              xml.enabled true
              xml.destination = file(\"\${buildDir}/reports/jacoco/result.xml\")
              html.enabled false
              csv.enabled false
            }
          }
          " >> build.gradle
      
      - name: Run Gradle Build
        run: ./gradlew clean build --warning-mode all --stacktrace
      
      - name: Analyze Test and/or Coverage Results
        if: always()
        uses: runforesight/foresight-test-kit-action@v1
        with:
          api_key: ${{ secrets.FORESIGHT_API_KEY }}
          test_framework: junit
          test_path: "./build/test-results/test/**"
          coverage_format: jacoco/xml
          coverage_path: "./build/reports/jacoco/*.xml"
